#!/usr/bin/env bash

# Generate html documentation.
in_files=("${PWD}/docs/retain-sync.1")
for file in "${in_files[@]}"; do
    groff -mandoc -Thtml < "$file" > "$file.html"
    python "${PWD}/scripts/man-format.py" "$file.html"
    git add "$file.html"
done
