#!/usr/bin/env python3

from zielen.daemon import main

if __name__ == "__main__":
    # Start program with profiler.
    # import profile
    # profile.run("main()")

    # Start program normally.
    main()
